name: unittest

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Run Unit Tests
      run: python -m unittest discover tests -p '*test*.py'
